// src/config/app.ts
export const AppConfig = {
  LUNCH_FOOD_BASE_INCOME: 8000,
  LUNCH_FOOD_OVERAGE_SHARE_PERCENT: 0.5, // 50%
  LUNCH_DRINK_SHARE_PERCENT: 0.25, // 25%

  DINNER_FOOD_OUR_SHARE_PERCENT: 0.75, // 75%
  DINNER_FOOD_COMMON_POOL_PERCENT: 0.25, // 25%
  DINNER_DRINK_COMMON_POOL_PERCENT: 0.25, // 25% (for drinks)
};
